name: f1vpn_node
services:
  vnstat:
    image: vergoh/vnstat:latest
    container_name: vnstat
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/lib/vnstat:/var/lib/vnstat
      - ./vnstat.conf:/etc/vnstat.conf
    environment:
      - HTTP_PORT=0

