---
- hosts: all
  vars:
    tailscale_path: "{{ ansible_env.HOME }}/tailscale-conf-{{ inventory_hostname }}.tar.gz"

  pre_tasks:
  - name: Ensure that all necessary environment variables are loaded
    ansible.builtin.assert:
      that:
        - new_username | length > 0
      fail_msg: "run `source ./.env` and load environment variables"

  tasks:
  - name: make backup file of tailscale conf dir
    become: yes
    community.general.archive:
      path: /var/lib/tailscale
      dest: "{{ tailscale_path }}"

  - name: fetch tailscale backup file from remote to local pwd 
    ansible.builtin.fetch:
      src: "{{ tailscale_path }}"
      dest: "../backup/{{ '%Y%m%d' | strftime }}/"
      flat: true

  - name: Copy backup files to Google Drive.
    delegate_to: localhost
    run_once: yes
    ansible.builtin.shell:
      cmd: rclone copy --exclude ".DS_Store" --progress backup/ google_drive_f1vpn:f1vpn/backup/
      chdir: ../
    