---
- hosts: all
  vars:
    tailscale_path: "{{ ansible_env.HOME }}/tailscale-conf-{{ inventory_hostname }}.tar.gz"
    vnstat_path: "{{ ansible_env.HOME }}/vnstat-conf-{{ inventory_hostname }}.tar.gz"

  pre_tasks:
  - name: Ensure that all necessary environment variables are loaded
    ansible.builtin.assert:
      that:
        - new_username | length > 0
      fail_msg: "run `source ./.env` and load environment variables"

  tasks:
  - name: make backup file of tailscale conf dir
    become: yes
    community.general.archive:
      path: /var/lib/tailscale
      dest: "{{ tailscale_path }}"

  - name: fetch tailscale backup file from remote to local pwd 
    ansible.builtin.fetch:
      src: "{{ tailscale_path }}"
      dest: "../backup/{{ '%Y%m%d' | strftime }}/"
      flat: true

  - name: make backup file of vnstat conf dir
    become: yes
    community.general.archive:
      path: /var/lib/vnstat
      dest: "{{ vnstat_path }}"

  - name: fetch vnstat backup file from remote to local pwd 
    ansible.builtin.fetch:
      src: "{{ vnstat_path }}"
      dest: "../backup/{{ '%Y%m%d' | strftime }}/"
      flat: true