---
- name: Copy utils directory
  ansible.builtin.copy:
    src: ./utils
    dest: "{{ ansible_env.HOME }}/"
    mode: preserve

- name: install deps for cron jobs
  become: yes
  ansible.builtin.apt:
    pkg:
      - jq
      - curl
    state: present

- name: configure crontab
  shell:
    cmd: "crontab utils.crontab"
    chdir: "{{ ansible_env.HOME }}/utils/"