---
- name: copy docker compose file
  ansible.builtin.copy:
    src: ./docker
    dest: "{{ ansible_env.HOME }}/"
    mode: '644'

- name: Run container
  shell:
    cmd: "sudo docker compose up -d"
    chdir: "{{ ansible_env.HOME }}/docker"